FROM nginx

LABEL version "1.0"
LABEL description "This is an example load balancer \
which sits in front of two webapp instances."
LABEL org.label-schema.schema-version "1.0"
LABEL org.label-schema.build-date "2016-04-12T23:20:50.52Z"
LABEL org.label-schema.name "webapp_demo-balancer"
LABEL org.label-schema.vcs-ref "279FA63"
LABEL org.label-schema.vcs-url "https://github.com/johnmccabe/talks/pug_london_may2017_lumogon/webapp_demo/balancer"
LABEL org.label-schema.vendor "John McCabe"

COPY nginx.conf /etc/nginx/nginx.conf